name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test ProServ.Tests/ProServ.Tests.csproj

      - name: Publish Server
        run: dotnet publish --configuration Release --no-build --output ./published/Server Server/ProServ.Server.csproj

      - name: Publish Client
        run: dotnet publish --configuration Release --no-build --output ./published/Client Client/ProServ.Client.csproj

      - name: Deploy Server to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "ProServ"
          publish-profile: ${{ secrets.AZURE_PROSERV_PUBLISH_KEY }}
          package: ./published/Server

      - name: Deploy Client to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "ProServClient"
          publish-profile: ${{ secrets.AZURE_PROSERVCLIENT_PUBLISH_KEY }}
          package: ./published/Client
